"""Taiwanese (16-tile) mahjong hand analysis."""

from .danger import (
    DECLARED_TAI,
    DangerAssessment,
    DangerDiscardAnalysis,
    OpponentView,
    RiverEntry,
    TenpaiAssessment,
    WaitShape,
    danger_score,
    fold_score,
    format_river,
    parse_river,
    rank_discards,
    tenpai_score,
)
from .analysis import (
    AnalysisContext,
    CalibrationContext,
    CalibrationProvider,
    DEFAULT_ANALYSIS_CONTEXT,
    HEURISTIC_FALLBACK,
)
from .calibration import Calibration, MIN_CELL_COUNT
from .config import DEFAULT_GAME_CONFIG, GameConfig, SCHEME_PRESETS
from .ev import (
    DeclarationAdvice,
    EVRankEntry,
    TileAccounting,
    WinValueContext,
    WinValueEstimate,
    deal_in_ev,
    declaration_ev,
    estimate_win_value,
    ev_rank,
    evaluate_pass,
    opponent_hazards,
    opponent_value_estimate,
    remaining_draws,
    survival_by_turn,
)
from .scoring import BASE_UNITS, DEFAULT_SCHEME, SCHEME_3_1, SCHEME_5_2, ScoreResult, ScoringScheme, WinContext, score_hand
from .shanten import shanten
from .simulate import SimResult, WinningTrial, win_probability, winning_trials
from .tiles import format_tiles, parse_tiles
from .ukeire import DiscardAnalysis, discard_analysis, ukeire

__all__ = [
    "BASE_UNITS",
    "DEFAULT_SCHEME",
    "SCHEME_3_1",
    "SCHEME_5_2",
    "ScoringScheme",
    "DangerAssessment",
    "DangerDiscardAnalysis",
    "Calibration",
    "CalibrationContext",
    "CalibrationProvider",
    "AnalysisContext",
    "DEFAULT_ANALYSIS_CONTEXT",
    "HEURISTIC_FALLBACK",
    "GameConfig",
    "DEFAULT_GAME_CONFIG",
    "SCHEME_PRESETS",
    "DeclarationAdvice",
    "DECLARED_TAI",
    "DiscardAnalysis",
    "EVRankEntry",
    "TileAccounting",
    "OpponentView",
    "RiverEntry",
    "SimResult",
    "WinningTrial",
    "WinValueContext",
    "WinValueEstimate",
    "MIN_CELL_COUNT",
    "TenpaiAssessment",
    "WaitShape",
    "danger_score",
    "deal_in_ev",
    "declaration_ev",
    "discard_analysis",
    "format_tiles",
    "format_river",
    "fold_score",
    "estimate_win_value",
    "ev_rank",
    "evaluate_pass",
    "opponent_hazards",
    "parse_river",
    "parse_tiles",
    "opponent_value_estimate",
    "remaining_draws",
    "rank_discards",
    "ScoreResult",
    "score_hand",
    "shanten",
    "WinContext",
    "tenpai_score",
    "survival_by_turn",
    "ukeire",
    "win_probability",
    "winning_trials",
]
