#!/usr/bin/env python3
# Source font: Noto Serif TC (NotoSerifTC.ttf), SIL Open Font License 1.1.
# Copyright 2012 Google Inc. All Rights Reserved.
"""Generate self-contained Noto Serif TC SVG outlines for Mahjong tile faces.

Usage:
    python3 scripts/gen_tile_faces.py

The script reads ~/.local/share/fonts/NotoSerifTC.ttf (an OFL-licensed
variable font), instantiates wght=700 when possible, and deterministically
writes server/static/js/tile-faces.js.  It needs fontTools, installable with:
    python3 -m pip install --user fonttools
"""

from __future__ import annotations

import json
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

try:
    from fontTools.varLib.instancer import instantiateVariableFont
except ImportError:  # Older fontTools can still extract the default outlines.
    instantiateVariableFont = None


FONT_PATH = Path.home() / ".local/share/fonts/NotoSerifTC.ttf"
OUTPUT_PATH = Path(__file__).resolve().parents[1] / "server/static/js/tile-faces.js"
GLYPHS = "一二三四五六七八九萬東南西北中發"
WEIGHT = 700


def js_string(value: object) -> str:
    """Return a compact, deterministic JavaScript string literal."""
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def main() -> None:
    if not FONT_PATH.is_file():
        raise SystemExit(f"OFL font not found: {FONT_PATH}")

    font = TTFont(FONT_PATH)
    if "fvar" in font and instantiateVariableFont:
        try:
            font = instantiateVariableFont(font, {"wght": WEIGHT}, inplace=False)
        except Exception as exc:  # Default outlines remain a valid OFL fallback.
            print(f"warning: could not instantiate wght={WEIGHT}: {exc}")

    units_per_em = font["head"].unitsPerEm
    ascent = font["OS/2"].sTypoAscender
    scale = 1000 / units_per_em
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"].metrics
    records: list[tuple[str, str, int, list[float]]] = []

    for char in GLYPHS:
        glyph_name = cmap.get(ord(char))
        if glyph_name is None:
            raise SystemExit(f"missing glyph for {char}")
        pen = SVGPathPen(glyph_set)
        transform = (scale, 0, 0, -scale, 0, ascent * scale)
        glyph_set[glyph_name].draw(TransformPen(pen, transform))
        bounds_pen = BoundsPen(glyph_set)
        glyph_set[glyph_name].draw(bounds_pen)
        x_min, y_min, x_max, y_max = bounds_pen.bounds or (0, 0, 0, 0)
        bbox = [
            round(x_min * scale, 3),
            round(ascent * scale - y_max * scale, 3),
            round(x_max * scale, 3),
            round(ascent * scale - y_min * scale, 3),
        ]
        records.append((char, pen.getCommands(), round(hmtx[glyph_name][0] * scale), bbox))

    lines = [
        "// Generated by scripts/gen_tile_faces.py; do not edit by hand.",
        "// Source: Noto Serif TC (NotoSerifTC.ttf), SIL Open Font License 1.1.",
        "// Copyright 2012 Google Inc. All Rights Reserved.",
        "",
        "export const TILE_FACE_FONT = Object.freeze({",
        "  family: 'Noto Serif TC',",
        "  license: 'SIL Open Font License 1.1',",
        f"  weight: {WEIGHT},",
        "  viewBox: '0 0 1000 1000',",
        "});",
        "",
        "export const TILE_GLYPHS = Object.freeze({",
    ]
    for char, path, advance, bbox in records:
        lines.append(
            f"  {js_string(char)}: Object.freeze({{path: {js_string(path)}, advance: {advance}, bbox: {js_string(bbox)}}}),"
        )
    lines.extend(["});", ""])
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
